### ISSUE TITLE
Why ParseWakeUpReceiver instead of Application

### ISSUE THREAD

**Issue by mobiRic** [FrostyElk/cordova-parse-plugin#2]
Hello Arne ( @frostyelkarne ),

I wonder if you would tell me briefly why you moved away from the Application initialisation to using the ParseWakeUpReceiver please?

I came across your plugin originally because it handled the automatic Parse initialisation. My initial intent was to modify another plugin to copy in my own Application class, like you originally did.

However you prefer using the broadcastreceiver instead of the application, despite saying it is "a brutal workaround". I like the decoupled approach, however I am also wary of future Android versions no longer "respecting" the load order of the receivers from the manifest, and wonder if it might not be better to go back to the application model for future-proofing reasons.

Many thanks,
Richard

**Comment by arnesikstrom** [comment]
Hi,
If I remember correctly I couldn't find a way to get it to work for the Intel XDK cloud build. The cloud build creates a fresh platform and then just installs the plugins and builds.

**Comment by mobiRic** [comment]
Thanks, that is interesting. I am building locally, so that would not be an issue for me, but I don't see any point in changing anything while it is still working.
